# Generated by Django 2.2.12 on 2020-04-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('projects', '0002_auto_20200116_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='upload',
            field=models.ManyToManyField(related_name='task_participants_upload', to='user.Profile'),
        ),
        migrations.CreateModel(
            name='TaskPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField()),
                ('write', models.BooleanField()),
                ('modify', models.BooleanField()),
                ('owner', models.BooleanField()),
                ('upload', models.BooleanField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_for_task', to='projects.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions_for_user', to='user.Profile')),
            ],
        ),
    ]
