# Generated by Django 2.2.12 on 2020-04-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200421_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskpermissions',
            old_name='user',
            new_name='profile',
        ),
    ]
