# Generated by Django 2.2.12 on 2020-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200421_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskpermissions',
            name='view_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskpermissions',
            name='modify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskpermissions',
            name='owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskpermissions',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskpermissions',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskpermissions',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
